version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
